### PR TITLE
Removes custom scrollbar styling

### PR DESCRIPTION
**Pull request by 1602**
So that user preferences can define scrollbar appearance (e.g. show scrollbar only on hover).

### CODE REVIEW

**Comment by inca** [comment]
Great idea btw! (scrollbar on hover)

**Comment by muzafarova** [comment]
This is user OS setting (scrollbar on hover) which we were overriding by CSS.. I believe it's not possible to force scrollbar on hover by CSS (I might be wrong)

@inca I'm going to merge and publish this one (for the first time 🎉) is it patch or should be "minor"? Is UDF relying on "tiny scrollbars" from this project?

**Comment by muzafarova** [comment]
image

this is it ^

**Comment by 1602** [comment]
Strictly speaking this is a breaking change, since it requires all clients to add some css to handle scrollbars (so that everything stays the same). Not sure what are the rules about this in css world (everything looks like a breaking change there).

Looking at amount of changes, looks like a patch.

**Comment by muzafarova** [comment]
Given the early stage of the project and amount of current clients
(Autopilot-UDF and test-runner), we agreed that this was just a patch :3

**Pull request merged**
