### PR TITLE
Variable conventions

### PR DESCRIPTION
**Pull request by inca**
This PR executes some of the ideas mentioned in README. They are isolated and simple enough to revert either as a whole or one-by-one (via simple renaming).

This **does not** include palette and colours.

Details:

- Adopt `--aspect--modifier` convention for variables. Reason: current inconsistency (`--gap-small` vs `--font__family--mono`), "element" part dropped because variables describe _traits_, not particular _things_ (hence, aspects as a term)
- `--border-color` variable moved to `--ctl-border-color`. Reason: "border" when used without context is an ambiguous term, this colour can be used in contexts which imply specific surroundings (e.g. white background, or adjacency to something gray-ish), which hurts overall componentization. Usage of `--border-color` outside basic components replaced with temporary palette colour which will get revisited when appropriate decisions are made.
- line-height variables are removed. Reason: 1) `--main` one was not used, 2) `--mono` one was inlined in the same manner as `p` inlines the value for content-specific stuff 3) base line height should be 1 (as was discussed at some point), so typeface doesn't affect this for all the components (only for content styles which are separate)
- `--border-radius` renamed to `--ctl-border-radius`. Reason: unify with `--ctl-*` family, partially same reason as for `--border-color`. Caveat: badge component uses `--ctl-border-radius` and this makes its intention more clear (e.g. use same border-radius as all controls do)

### CODE REVIEW

**Comment by muzafarova** [comment]
line-height variable was designed to be used specifically in copy (fancy name for content in design mockups) so this is probably lack of description than uselessness

So the intention is to pre-define base font size / line height aspect that works for base and mono fonts. This way (if we ever change base or mono font) we won't go through all the components with copy to check if aspect ratio still fine. Just a nice practice. 

Base line-height is 1 indeed, makes development much more predictable.

**Comment by muzafarova** [comment]
all the rest is fine except `--ctl-`... is it named after "control"? Should we use same variable for other borders which are not control element borders?

**Comment by muzafarova** [comment]
`--ctl-height: 24px` should become relative `--ctl-height: 2em`

we probably should avoid any heights hardcoded in pixels to unlock UDF scaling possibilities

**Comment by muzafarova** [comment]
Part of https://github.com/universalbasket/engineering/issues/376

**Comment by inca** [comment]
Is this ok to merge @muzafarova?

**Pull request merged**
